branches:
  only:
    - master

language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy:v2 ./udagram-reverseproxy
  - docker tag reverseproxy:v2 ngotu/reverseproxy:v2

  - docker build -t udagram-frontend:v2 -f ./udagram-frontend
  - docker tag udagram-frontend:v2 ngotu/udagram-frontend:v2

  - docker build -t udagram-api-user:v2 -f ./udagram-api-user
  - docker tag udagram-api-user:v2 ngotu/udagram-api-user:v2

  - docker build -t udagram-api-feed:v2 -f ./udagram-api-feed
  - docker tag udagram-api-feed:v2 ngotu/udagram-api-feed:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push  ngotu/reverseproxy:v2
  - docker push  ngotu/udagram-frontend:v2
  - docker push  ngotu/udagram-api-user:v2
  - docker push  ngotu/udagram-api-feed:v2