branches:
  only:
    - master

language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy:v1 ./udagram-reverseproxy
  - docker tag udagram-reverseproxy:v1 ngotu/reverseproxy:v1

  - docker build -t udagram-frontend:v1 -f ./udagram-frontend
  - docker tag udagram-frontend:v1 ngotu/udagram-frontend:v1

  - docker build -t udagram-api-user:v1 -f ./udagram-api-user
  - docker tag udagram-api-user:v1 ngotu/udagram-api-user:v1

  - docker build -t udagram-api-feed:v1 -f ./udagram-api-feed
  - docker tag udagram-api-feed:v1 ngotu/udagram-api-feed:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push  ngotu/reverseproxy:v1
  - docker push  ngotu/udagram-frontend:v1
  - docker push  ngotu/udagram-api-user:v1
  - docker push  ngotu/udagram-api-feed:v1